name: scp files
on: [push]
jobs:

  build:
    name: COPY FILES
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Remove Files
      uses: JesseTG/rm@v1.0.3
      with:
        path: /www/wwwroot/blog.retrogeek.lat/themes/RetroGeekLatam
