name: scp files
on: [push]
jobs:

  build:
    name: COPY FILES
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: copy file via ssh password
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSHKEY }}
        port: ${{ secrets.PORT }}
        source: .
        target: /www/wwwroot/blog.retrogeek.lat/themes/RetroGeekLatam